name: peaking_test
dependencies:
- python=3.11.4
- pandas>=0.24
- scikit-learn
- scipy
- numpy
- matplotlib
- seaborn
- jupyterlab
- pytest
- pycountry
- openpyxl
- pip
- pip:
  - pandas_indexing
  - pylint==2.15.0
  - astroid==2.12.4